export interface Salon {
  name: string;
  image: string;
  location: string;
  distance?: string;
  rating: string;
  type: string;
  hours: string;
  services?: string;
}

export const salons: Salon[] = [
  {
    name: "Bella Bliss Salon",
    image: "/images/t1.jpg",
    location: "1234 Elm St, Springfield, IL",
    distance: "5.2 km",
    rating: "4.5",
    type: "Unisex",
    hours: "8:00 am - 6:00 pm",
  },
  {
    name: "Modern Touch Hair Studio",
    image: "/images/t2.jpg",
    location: "5678 Oak Dr, Austin, TX",
    distance: "7 km",
    rating: "4.6",
    type: "Male",
    hours: "9:30 am - 7:30 pm",
  },
  {
    name: "Golden Glow Beauty Lounge",
    image: "/images/t3.jpg",
    location: "4321 Pine Ave, Miami, FL",
    distance: "10 km",
    rating: "4.7",
    type: "Unisex",
    hours: "10:00 am - 8:30 pm",
  },
  {
    name: "Tranquil Tresses Spa",
    image: "/images/t4.jpg",
    location: "789 Cedar Rd, Seattle, WA",
    distance: "12.5 km",
    rating: "4.4",
    type: "Female",
    hours: "8:30 am - 6:00 pm",
  },
  {
    name: "Lavish Locks Hair Studio",
    image: "/images/t5.jpg",
    location: "222 Sunset Blvd, Los Angeles, CA",
    distance: "6.3 km",
    rating: "4.6",
    type: "Female",
    hours: "9:00 am - 7:00 pm",
  },
  {
    name: "The Gents Grooming Club",
    image: "/images/t6.jpg",
    location: "145 King St, Boston, MA",
    distance: "8.7 km",
    rating: "4.7",
    type: "Unisex",
    hours: "9:00 am - 8:00 pm",
  },
  {
    name: "Dapper Den Barbers",
    image: "/images/t7.jpg",
    location: "789 Broadway, New York, NY",
    distance: "11.5 km",
    rating: "4.8",
    type: "Male",
    hours: "10:00 am - 9:30 pm",
  },
  {
    name: "Opulent Beauty Haven",
    image: "/images/t8.jpg",
    location: "555 Ocean Ave, San Diego, CA",
    distance: "13 km",
    rating: "4.7",
    type: "Unisex",
    hours: "9:00 am - 6:30 pm",
  },
  {
    name: "Elite Hair Studio",
    image: "/images/t6.jpg",
    location: "321 Maple St, Denver, CO",
    distance: "9.4 km",
    rating: "4.5",
    type: "Unisex",
    hours: "8:00 am - 7:00 pm",
  },
  {
    name: "Silken Strands Salon",
    image: "/images/t4.jpg",
    location: "876 Willow Ave, San Francisco, CA",
    distance: "14 km",
    rating: "4.6",
    type: "Female",
    hours: "10:00 am - 8:00 pm",
  },
  {
    name: "The Prestige Barber Lounge",
    image: "/images/t1.jpg",
    location: "159 Park Lane, Chicago, IL",
    distance: "10.8 km",
    rating: "4.7",
    type: "Male",
    hours: "9:30 am - 9:00 pm",
  },{
    name: "Golden Glow Beauty Lounge",
    image: "/images/t3.jpg",
    location: "4321 Pine Ave, Miami, FL",
    distance: "10 km",
    rating: "4.7",
    type: "Unisex",
    hours: "10:00 am - 8:30 pm",
  }
];

export const topRatedSalons: Salon[] = [
  {
      name: "Elite Hair & Spa",
      image: "/images/s1.jpg",
      location: "987 Main St, Dallas, TX",
      rating: "4.9",
      type: "Unisex",
      services: "VIP hair styling, rejuvenating spa treatments, scalp therapy",
      hours: "9:00 am - 7:30 pm",
  },
  {
      name: "The Prestige Salon",
      image: "/images/s2.jpg",
      location: "321 River Rd, Denver, CO",
      rating: "4.8",
      type: "Male",
      services: "Exclusive haircuts, beard sculpting, premium grooming",
      hours: "10:30 am - 8:00 pm",
  },
  {
      name: "Velvet Touch Hair Lounge",
      image: "/images/s3.jpg",
      location: "444 Willow Ave, San Francisco, CA",
      rating: "5.0",
      type: "Unisex",
      services: "Precision hairstyling, hair detox treatments, relaxation spa",
      hours: "9:30 am - 8:30 pm",
  },
  {
      name: "Serene Beauty Retreat",
      image: "/images/s4.jpg",
      location: "789 Maple Ln, Portland, OR",
      rating: "4.7",
      type: "Female",
      services: "Organic facials, luxurious body treatments, manicure & pedicure",
      hours: "8:00 am - 6:00 pm",
  },
  {
      name: "Glamour Haven Studio",
      image: "/images/s5.jpg",
      location: "852 Glam St, Miami Beach, FL",
      rating: "4.9",
      type: "Female",
      services: "Professional makeup, advanced skincare, bridal packages",
      hours: "9:00 am - 7:30 pm",
  },
  {
      name: "Supreme Hair Atelier",
      image: "/images/s6.jpg",
      location: "963 Luxe Blvd, Las Vegas, NV",
      rating: "4.8",
      type: "Unisex",
      services: "Innovative hair color, keratin treatments, deep conditioning",
      hours: "9:30 am - 8:30 pm",
  },
  {
      name: "Refined Gents Barbershop",
      image: "/images/s7.jpg",
      location: "741 Broadway, Chicago, IL",
      rating: "4.9",
      type: "Male",
      services: "Artisan haircuts, premium beard trims, head massage",
      hours: "11:00 am - 9:30 pm",
  },
  {
      name: "Lush Locks Hair & Spa",
      image: "/images/s8.jpg",
      location: "888 Sunset Ave, San Jose, CA",
      rating: "4.9",
      type: "Unisex",
      services: "Hair extensions, revitalizing hair therapy, spa facials",
      hours: "9:30 am - 7:30 pm",
  }
];


export const recommendedSalons: Salon[] = [
  {
    name: "Elysian Hair Studio",
    image: "/images/r1.jpg",
    location: "1235 Sunset Blvd, Los Angeles, California",
    rating: "4.9",
    type: "Unisex",
    services: "Signature haircuts, hair coloring, scalp massage",
    hours: "9:00 am - 8:00 pm",
  },
  {
    name: "Majestic Mane Salon",
    image: "/images/r2.jpg",
    location: "221 Baker St, New York, NY",
    rating: "4.7",
    type: "Female",
    services: "Luxury hair treatments, balayage, hair spa",
    hours: "10:00 am - 7:30 pm",
  },
  {
    name: "The Grooming Den",
    image: "/images/r3.jpg",
    location: "3901 River Rd, Dallas, Texas",
    rating: "4.8",
    type: "Male",
    services: "Classic cuts, beard sculpting, scalp rejuvenation",
    hours: "11:00 am - 9:00 pm",
  },
  {
    name: "Aurora Beauty Lounge",
    image: "/images/r4.jpg",
    location: "786 Greenway Ave, San Francisco, California",
    rating: "4.6",
    type: "Unisex",
    services: "Makeup artistry, hair styling, bridal beauty",
    hours: "9:30 am - 6:30 pm",
  },
  {
    name: "Pure Bliss Hair & Spa",
    image: "/images/r5.jpg",
    location: "905 Ocean Dr, Miami, Florida",
    rating: "4.9",
    type: "Female",
    services: "Organic facials, deep hair conditioning, wellness spa",
    hours: "8:30 am - 7:00 pm",
  },
  {
    name: "Refined Cuts Barbershop",
    image: "/images/r6.jpg",
    location: "5005 Main St, Houston, Texas",
    rating: "4.8",
    type: "Male",
    services: "Precision fades, hot towel shaves, beard care",
    hours: "10:00 am - 9:00 pm",
  },
  {
    name: "Lush Locks Beauty Studio",
    image: "/images/r7.jpg",
    location: "2121 Pine St, Seattle, Washington",
    rating: "4.7",
    type: "Unisex",
    services: "Hair extensions, keratin treatments, scalp detox",
    hours: "9:00 am - 7:30 pm",
  },
  {
    name: "Zenith Hair Retreat",
    image: "/images/r8.jpg",
    location: "890 Grand Ave, Chicago, Illinois",
    rating: "4.8",
    type: "Unisex",
    services: "Relaxing scalp therapies, deep conditioning, expert styling",
    hours: "9:30 am - 8:00 pm",
  }
];